import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';
import './assets/advanced-slied.aio.main.css';
import './assets/advanced-slied.aio.main.js';
import './assets/advanced-slied.css';
import './assets/advanced-slied.js';
import './assets/advanced-slied.main.js';
import './assets/animation-noscript.aio.main.css';
import './assets/animation-noscript.css';
import './assets/aos-aio.main.css';
import './assets/aos-aio.main.js';
import './assets/aos.css';
import './assets/aos.js';
import './assets/back-to-top.aio.main.css';
import './assets/back-to-top.aio.main.js';
import './assets/back-to-top.css';
import './assets/back-to-top.js';
import './assets/base-aio.main.css';
import './assets/base.css';
import './assets/cart-drawer.aio.main.js';
import './assets/cart-drawer.js';
import './assets/cart-notification.aio.main.js';
import './assets/cart-notification.js';
import './assets/cart.aio.main.js';
import './assets/cart.js';
import './assets/collapsable-contant.aio.main.css';
import './assets/collapsable-contant.css';
import './assets/collection-list-style.aio.main.css';
import './assets/collection-list-style.css';
import './assets/component-accrodion.aio.main.css';
import './assets/component-accrodion.css';
import './assets/component-artical-card.aio.main.css';
import './assets/component-artical-card.css';
import './assets/component-breadcrumbs.aio.main.css';
import './assets/component-breadcrumbs.css';
import './assets/component-card.aio.main.css';
import './assets/component-card.css';
import './assets/component-cart-drawer.aio.main.css';
import './assets/component-cart-drawer.css';
import './assets/component-cart-items.aio.main.css';
import './assets/component-cart-items.css';
import './assets/component-cart-notification.aio.main.css';
import './assets/component-cart-notification.css';
import './assets/component-cart.aio.main.css';
import './assets/component-cart.css';
import './assets/component-collection-hero.aio.main.css';
import './assets/component-collection-hero.css';
import './assets/component-complementary-product.aio.main.css';
import './assets/component-complementary-product.css';
import './assets/component-deferred-main.css';
import './assets/component-deferred-media.aio.main.css';
import './assets/component-desktop-menu-drawer.aio.main.css';
import './assets/component-desktop-menu-drawer.css';
import './assets/component-discount.aio.main.css';
import './assets/component-discount.css';
import './assets/component-fecets.aio.main.css';
import './assets/component-fecets.css';
import './assets/component-image-with-text.aio.main.css';
import './assets/component-image-with-text.css';
import './assets/component-list-menu.aio.main.css';
import './assets/component-list-menu.css';
import './assets/component-list-payment.aio.main.css';
import './assets/component-list-payment.css';
import './assets/component-list-social.aio.main.css';
import './assets/component-list-social.css';
import './assets/component-loading-overlay.aio.main.css';
import './assets/component-loading-overlay.css';
import './assets/component-mega-menu-animation.aio.main.css';
import './assets/component-mega-menu-animation.css';
import './assets/component-mega-menu.aio.main.css';
import './assets/component-mega-menu.css';
import './assets/component-menu-darwer.aio.main.css';
import './assets/component-menu-drawer.css';
import './assets/component-model-video.aio.main.css';
import './assets/component-model-video.css';
import './assets/component-model-viewer-ui.aio.main.css';
import './assets/component-model-viewer-ui.css';

import App from './App.jsx';

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
